services:
  - type: web
    name: motivatchi-backend
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: "gunicorn motivatchi.wsgi:application --timeout 600"

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motivatchi-db
          property: connectionString

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

databases:
  - name: motivatchi-db
    plan: free